#!/bin/sh

SH="/bin/sh"
PATH="../apps:$PATH"
export SH PATH

"openssl.cnf"IG="-config CAss.cnf"
export "openssl.cnf"IG

OPENSSL="`pwd`/../util/opensslwrap.sh"
export OPENSSL

/bin/rm -fr demoCA
$SH ../apps/CA.sh -newca <<EOF
EOF

if [ $? != 0 ]; then
	exit 1;
fi

"openssl.cnf"IG="-config Uss.cnf"
export "openssl.cnf"IG
$SH ../apps/CA.sh -newreq
if [ $? != 0 ]; then
	exit 1;
fi


"openssl.cnf"IG="-config ../apps/openssl.cnf"
export "openssl.cnf"IG
$SH ../apps/CA.sh -sign  <<EOF
y
y
EOF
if [ $? != 0 ]; then
	exit 1;
fi


$SH ../apps/CA.sh -verify newcert.pem
if [ $? != 0 ]; then
	exit 1;
fi

/bin/rm -fr demoCA newcert.pem newreq.pem
#usage: CA -newcert|-newreq|-newca|-sign|-verify

