/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/dso.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_DSO, func, 0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_DSO, 0, reason)

static ERR_STRING_DATA DSO_str_functs[] = {
    { ERR_FUNC(DSO_F_DLFCN_BIND_FUNC), "DLFCN_BIND_FUNC" },
    { ERR_FUNC(DSO_F_DLFCN_BIND_VAR), "DLFCN_BIND_VAR" },
    { ERR_FUNC(DSO_F_DLFCN_LOAD), "DLFCN_LOAD" },
    { ERR_FUNC(DSO_F_DLFCN_MERGER), "DLFCN_MERGER" },
    { ERR_FUNC(DSO_F_DLFCN_NAME_CONVERTER), "DLFCN_NAME_CONVERTER" },
    { ERR_FUNC(DSO_F_DLFCN_UNLOAD), "DLFCN_UNLOAD" },
    { ERR_FUNC(DSO_F_DL_BIND_FUNC), "DL_BIND_FUNC" },
    { ERR_FUNC(DSO_F_DL_BIND_VAR), "DL_BIND_VAR" },
    { ERR_FUNC(DSO_F_DL_LOAD), "DL_LOAD" },
    { ERR_FUNC(DSO_F_DL_MERGER), "DL_MERGER" },
    { ERR_FUNC(DSO_F_DL_NAME_CONVERTER), "DL_NAME_CONVERTER" },
    { ERR_FUNC(DSO_F_DL_UNLOAD), "DL_UNLOAD" },
    { ERR_FUNC(DSO_F_DSO_BIND_FUNC), "DSO_BIND_FUNC" },
    { ERR_FUNC(DSO_F_DSO_BIND_VAR), "DSO_BIND_VAR" },
    { ERR_FUNC(DSO_F_DSO_CONVERT_FILENAME), "DSO_CONVERT_FILENAME" },
    { ERR_FUNC(DSO_F_DSO_CTRL), "DSO_CTRL" },
    { ERR_FUNC(DSO_F_DSO_FREE), "DSO_FREE" },
    { ERR_FUNC(DSO_F_DSO_GET_FILENAME), "DSO_GET_FILENAME" },
    { ERR_FUNC(DSO_F_DSO_GET_LOADED_FILENAME), "DSO_GET_LOADED_FILENAME" },
    { ERR_FUNC(DSO_F_DSO_GLOBAL_LOOKUP), "DSO_GLOBAL_LOOKUP" },
    { ERR_FUNC(DSO_F_DSO_LOAD), "DSO_LOAD" },
    { ERR_FUNC(DSO_F_DSO_MERGE), "DSO_MERGE" },
    { ERR_FUNC(DSO_F_DSO_NEW_METHOD), "DSO_NEW_METHOD" },
    { ERR_FUNC(DSO_F_DSO_PATHBYADDR), "DSO_PATHBYADDR" },
    { ERR_FUNC(DSO_F_DSO_SET_FILENAME), "DSO_SET_FILENAME" },
    { ERR_FUNC(DSO_F_DSO_SET_NAME_CONVERTER), "DSO_SET_NAME_CONVERTER" },
    { ERR_FUNC(DSO_F_DSO_UP_REF), "DSO_UP_REF" },
    { ERR_FUNC(DSO_F_GLOBAL_LOOKUP_FUNC), "GLOBAL_LOOKUP_FUNC" },
    { ERR_FUNC(DSO_F_PATHBYADDR), "PATHBYADDR" },
    { ERR_FUNC(DSO_F_WIN32_BIND_FUNC), "WIN32_BIND_FUNC" },
    { ERR_FUNC(DSO_F_WIN32_BIND_VAR), "WIN32_BIND_VAR" },
    { ERR_FUNC(DSO_F_WIN32_GLOBALLOOKUP), "WIN32_GLOBALLOOKUP" },
    { ERR_FUNC(DSO_F_WIN32_GLOBALLOOKUP_FUNC), "WIN32_GLOBALLOOKUP_FUNC" },
    { ERR_FUNC(DSO_F_WIN32_JOINER), "WIN32_JOINER" },
    { ERR_FUNC(DSO_F_WIN32_LOAD), "WIN32_LOAD" },
    { ERR_FUNC(DSO_F_WIN32_MERGER), "WIN32_MERGER" },
    { ERR_FUNC(DSO_F_WIN32_NAME_CONVERTER), "WIN32_NAME_CONVERTER" },
    { ERR_FUNC(DSO_F_WIN32_PATHBYADDR), "WIN32_PATHBYADDR" },
    { ERR_FUNC(DSO_F_WIN32_SPLITTER), "WIN32_SPLITTER" },
    { ERR_FUNC(DSO_F_WIN32_UNLOAD), "WIN32_UNLOAD" },
    { 0, NULL }
};

static ERR_STRING_DATA DSO_str_reasons[] = {
    { ERR_REASON(DSO_R_CTRL_FAILED), "ctrl failed" },
    { ERR_REASON(DSO_R_DSO_ALREADY_LOADED), "dso already loaded" },
    { ERR_REASON(DSO_R_EMPTY_FILE_STRUCTURE), "empty file structure" },
    { ERR_REASON(DSO_R_FAILURE), "failure" },
    { ERR_REASON(DSO_R_FILENAME_TOO_BIG), "filename too big" },
    { ERR_REASON(DSO_R_FINISH_FAILED), "finish failed" },
    { ERR_REASON(DSO_R_INCORRECT_FILE_SYNTAX), "incorrect file syntax" },
    { ERR_REASON(DSO_R_LOAD_FAILED), "load failed" },
    { ERR_REASON(DSO_R_NAME_TRANSLATION_FAILED), "name translation failed" },
    { ERR_REASON(DSO_R_NO_FILENAME), "no filename" },
    { ERR_REASON(DSO_R_NO_FILE_SPECIFICATION), "no file specification" },
    { ERR_REASON(DSO_R_NULL_HANDLE), "null handle" },
    { ERR_REASON(DSO_R_SET_FILENAME_FAILED), "set filename failed" },
    { ERR_REASON(DSO_R_STACK_ERROR), "stack error" },
    { ERR_REASON(DSO_R_SYM_FAILURE), "sym failure" },
    { ERR_REASON(DSO_R_UNLOAD_FAILED), "unload failed" },
    { ERR_REASON(DSO_R_UNSUPPORTED), "unsupported" },
    { 0, NULL }
};

#endif

void ERR_load_DSO_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(DSO_str_functs[0].error) == NULL) {
        ERR_load_strings(0, DSO_str_functs);
        ERR_load_strings(0, DSO_str_reasons);
    }
#endif
}
