/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/ts.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_TS, func, 0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_TS, 0, reason)

static ERR_STRING_DATA TS_str_functs[] = {
    { ERR_FUNC(TS_F_D2I_TS_RESP), "D2I_TS_RESP" },
    { ERR_FUNC(TS_F_DEF_SERIAL_CB), "DEF_SERIAL_CB" },
    { ERR_FUNC(TS_F_DEF_TIME_CB), "DEF_TIME_CB" },
    { ERR_FUNC(TS_F_ESS_ADD_SIGNING_CERT), "ESS_ADD_SIGNING_CERT" },
    { ERR_FUNC(TS_F_ESS_CERT_ID_NEW_INIT), "ESS_CERT_ID_NEW_INIT" },
    { ERR_FUNC(TS_F_ESS_SIGNING_CERT_NEW_INIT), "ESS_SIGNING_CERT_NEW_INIT" },
    { ERR_FUNC(TS_F_INT_TS_RESP_VERIFY_TOKEN), "INT_TS_RESP_VERIFY_TOKEN" },
    { ERR_FUNC(TS_F_PKCS7_TO_TS_TST_INFO), "PKCS7_TO_TS_TST_INFO" },
    { ERR_FUNC(TS_F_TS_ACCURACY_SET_MICROS), "TS_ACCURACY_SET_MICROS" },
    { ERR_FUNC(TS_F_TS_ACCURACY_SET_MILLIS), "TS_ACCURACY_SET_MILLIS" },
    { ERR_FUNC(TS_F_TS_ACCURACY_SET_SECONDS), "TS_ACCURACY_SET_SECONDS" },
    { ERR_FUNC(TS_F_TS_CHECK_IMPRINTS), "TS_CHECK_IMPRINTS" },
    { ERR_FUNC(TS_F_TS_CHECK_NONCES), "TS_CHECK_NONCES" },
    { ERR_FUNC(TS_F_TS_CHECK_POLICY), "TS_CHECK_POLICY" },
    { ERR_FUNC(TS_F_TS_CHECK_SIGNING_CERTS), "TS_CHECK_SIGNING_CERTS" },
    { ERR_FUNC(TS_F_TS_CHECK_STATUS_INFO), "TS_CHECK_STATUS_INFO" },
    { ERR_FUNC(TS_F_TS_COMPUTE_IMPRINT), "TS_COMPUTE_IMPRINT" },
    { ERR_FUNC(TS_F_TS_CONF_SET_DEFAULT_ENGINE), "TS_CONF_SET_DEFAULT_ENGINE" },
    { ERR_FUNC(TS_F_TS_GET_STATUS_TEXT), "TS_GET_STATUS_TEXT" },
    { ERR_FUNC(TS_F_TS_MSG_IMPRINT_SET_ALGO), "TS_MSG_IMPRINT_SET_ALGO" },
    { ERR_FUNC(TS_F_TS_REQ_SET_MSG_IMPRINT), "TS_REQ_SET_MSG_IMPRINT" },
    { ERR_FUNC(TS_F_TS_REQ_SET_NONCE), "TS_REQ_SET_NONCE" },
    { ERR_FUNC(TS_F_TS_REQ_SET_POLICY_ID), "TS_REQ_SET_POLICY_ID" },
    { ERR_FUNC(TS_F_TS_RESP_CREATE_RESPONSE), "TS_RESP_CREATE_RESPONSE" },
    { ERR_FUNC(TS_F_TS_RESP_CREATE_TST_INFO), "TS_RESP_CREATE_TST_INFO" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_ADD_FAILURE_INFO),
     "TS_RESP_CTX_ADD_FAILURE_INFO" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_ADD_MD), "TS_RESP_CTX_ADD_MD" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_ADD_POLICY), "TS_RESP_CTX_ADD_POLICY" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_NEW), "TS_RESP_CTX_NEW" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_SET_ACCURACY), "TS_RESP_CTX_SET_ACCURACY" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_SET_CERTS), "TS_RESP_CTX_SET_CERTS" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_SET_DEF_POLICY), "TS_RESP_CTX_SET_DEF_POLICY" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_SET_SIGNER_CERT),
     "TS_RESP_CTX_SET_SIGNER_CERT" },
    { ERR_FUNC(TS_F_TS_RESP_CTX_SET_STATUS_INFO),
     "TS_RESP_CTX_SET_STATUS_INFO" },
    { ERR_FUNC(TS_F_TS_RESP_GET_POLICY), "TS_RESP_GET_POLICY" },
    { ERR_FUNC(TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION),
     "TS_RESP_SET_GENTIME_WITH_PRECISION" },
    { ERR_FUNC(TS_F_TS_RESP_SET_STATUS_INFO), "TS_RESP_SET_STATUS_INFO" },
    { ERR_FUNC(TS_F_TS_RESP_SET_TST_INFO), "TS_RESP_SET_TST_INFO" },
    { ERR_FUNC(TS_F_TS_RESP_SIGN), "TS_RESP_SIGN" },
    { ERR_FUNC(TS_F_TS_RESP_VERIFY_SIGNATURE), "TS_RESP_VERIFY_SIGNATURE" },
    { ERR_FUNC(TS_F_TS_RESP_VERIFY_TOKEN), "TS_RESP_VERIFY_TOKEN" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_ACCURACY), "TS_TST_INFO_SET_ACCURACY" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_MSG_IMPRINT),
     "TS_TST_INFO_SET_MSG_IMPRINT" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_NONCE), "TS_TST_INFO_SET_NONCE" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_POLICY_ID), "TS_TST_INFO_SET_POLICY_ID" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_SERIAL), "TS_TST_INFO_SET_SERIAL" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_TIME), "TS_TST_INFO_SET_TIME" },
    { ERR_FUNC(TS_F_TS_TST_INFO_SET_TSA), "TS_TST_INFO_SET_TSA" },
    { ERR_FUNC(TS_F_TS_VERIFY), "TS_VERIFY" },
    { ERR_FUNC(TS_F_TS_VERIFY_CERT), "TS_VERIFY_CERT" },
    { ERR_FUNC(TS_F_TS_VERIFY_CTX_NEW), "TS_VERIFY_CTX_NEW" },
    { 0, NULL }
};

static ERR_STRING_DATA TS_str_reasons[] = {
    { ERR_REASON(TS_R_BAD_PKCS7_TYPE), "bad pkcs7 type" },
    { ERR_REASON(TS_R_BAD_TYPE), "bad type" },
    { ERR_REASON(TS_R_CERTIFICATE_VERIFY_ERROR), "certificate verify error" },
    { ERR_REASON(TS_R_COULD_NOT_SET_ENGINE), "could not set engine" },
    { ERR_REASON(TS_R_COULD_NOT_SET_TIME), "could not set time" },
    { ERR_REASON(TS_R_D2I_TS_RESP_INT_FAILED), "d2i ts resp int failed" },
    { ERR_REASON(TS_R_DETACHED_CONTENT), "detached content" },
    { ERR_REASON(TS_R_ESS_ADD_SIGNING_CERT_ERROR),
     "ess add signing cert error" },
    { ERR_REASON(TS_R_ESS_SIGNING_CERTIFICATE_ERROR),
     "ess signing certificate error" },
    { ERR_REASON(TS_R_INVALID_NULL_POINTER), "invalid null pointer" },
    { ERR_REASON(TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE),
     "invalid signer certificate purpose" },
    { ERR_REASON(TS_R_MESSAGE_IMPRINT_MISMATCH), "message imprint mismatch" },
    { ERR_REASON(TS_R_NONCE_MISMATCH), "nonce mismatch" },
    { ERR_REASON(TS_R_NONCE_NOT_RETURNED), "nonce not returned" },
    { ERR_REASON(TS_R_NO_CONTENT), "no content" },
    { ERR_REASON(TS_R_NO_TIME_STAMP_TOKEN), "no time stamp token" },
    { ERR_REASON(TS_R_PKCS7_ADD_SIGNATURE_ERROR), "pkcs7 add signature error" },
    { ERR_REASON(TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR),
     "pkcs7 add signed attr error" },
    { ERR_REASON(TS_R_PKCS7_TO_TS_TST_INFO_FAILED),
     "pkcs7 to ts tst info failed" },
    { ERR_REASON(TS_R_POLICY_MISMATCH), "policy mismatch" },
    { ERR_REASON(TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE),
     "private key does not match certificate" },
    { ERR_REASON(TS_R_RESPONSE_SETUP_ERROR), "response setup error" },
    { ERR_REASON(TS_R_SIGNATURE_FAILURE), "signature failure" },
    { ERR_REASON(TS_R_THERE_MUST_BE_ONE_SIGNER), "there must be one signer" },
    { ERR_REASON(TS_R_TIME_SYSCALL_ERROR), "time syscall error" },
    { ERR_REASON(TS_R_TOKEN_NOT_PRESENT), "token not present" },
    { ERR_REASON(TS_R_TOKEN_PRESENT), "token present" },
    { ERR_REASON(TS_R_TSA_NAME_MISMATCH), "tsa name mismatch" },
    { ERR_REASON(TS_R_TSA_UNTRUSTED), "tsa untrusted" },
    { ERR_REASON(TS_R_TST_INFO_SETUP_ERROR), "tst info setup error" },
    { ERR_REASON(TS_R_TS_DATASIGN), "ts datasign" },
    { ERR_REASON(TS_R_UNACCEPTABLE_POLICY), "unacceptable policy" },
    { ERR_REASON(TS_R_UNSUPPORTED_MD_ALGORITHM), "unsupported md algorithm" },
    { ERR_REASON(TS_R_UNSUPPORTED_VERSION), "unsupported version" },
    { ERR_REASON(TS_R_WRONG_CONTENT_TYPE), "wrong content type" },
    { 0, NULL }
};

#endif

void ERR_load_TS_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(TS_str_functs[0].error) == NULL) {
        ERR_load_strings(0, TS_str_functs);
        ERR_load_strings(0, TS_str_reasons);
    }
#endif
}
