/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/dsa.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_DSA, func, 0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_DSA, 0, reason)

static ERR_STRING_DATA DSA_str_functs[] = {
    { ERR_FUNC(DSA_F_D2I_DSA_SIG), "D2I_DSA_SIG" },
    { ERR_FUNC(DSA_F_DO_DSA_PRINT), "DO_DSA_PRINT" },
    { ERR_FUNC(DSA_F_DSAPARAMS_PRINT), "DSAPARAMS_PRINT" },
    { ERR_FUNC(DSA_F_DSAPARAMS_PRINT_FP), "DSAPARAMS_PRINT_FP" },
    { ERR_FUNC(DSA_F_DSA_BUILTIN_PARAMGEN2), "DSA_BUILTIN_PARAMGEN2" },
    { ERR_FUNC(DSA_F_DSA_DO_SIGN), "DSA_DO_SIGN" },
    { ERR_FUNC(DSA_F_DSA_DO_VERIFY), "DSA_DO_VERIFY" },
    { ERR_FUNC(DSA_F_DSA_GENERATE_KEY), "DSA_GENERATE_KEY" },
    { ERR_FUNC(DSA_F_DSA_GENERATE_PARAMETERS_EX), "DSA_GENERATE_PARAMETERS_EX" },
    { ERR_FUNC(DSA_F_DSA_NEW_METHOD), "DSA_NEW_METHOD" },
    { ERR_FUNC(DSA_F_DSA_PARAM_DECODE), "DSA_PARAM_DECODE" },
    { ERR_FUNC(DSA_F_DSA_PRINT_FP), "DSA_PRINT_FP" },
    { ERR_FUNC(DSA_F_DSA_PRIV_DECODE), "DSA_PRIV_DECODE" },
    { ERR_FUNC(DSA_F_DSA_PRIV_ENCODE), "DSA_PRIV_ENCODE" },
    { ERR_FUNC(DSA_F_DSA_PUB_DECODE), "DSA_PUB_DECODE" },
    { ERR_FUNC(DSA_F_DSA_PUB_ENCODE), "DSA_PUB_ENCODE" },
    { ERR_FUNC(DSA_F_DSA_SIGN), "DSA_SIGN" },
    { ERR_FUNC(DSA_F_DSA_SIGN_SETUP), "DSA_SIGN_SETUP" },
    { ERR_FUNC(DSA_F_DSA_SIG_NEW), "DSA_SIG_NEW" },
    { ERR_FUNC(DSA_F_DSA_SIG_PRINT), "DSA_SIG_PRINT" },
    { ERR_FUNC(DSA_F_DSA_VERIFY), "DSA_VERIFY" },
    { ERR_FUNC(DSA_F_I2D_DSA_SIG), "I2D_DSA_SIG" },
    { ERR_FUNC(DSA_F_OLD_DSA_PRIV_DECODE), "OLD_DSA_PRIV_DECODE" },
    { ERR_FUNC(DSA_F_PKEY_DSA_CTRL), "PKEY_DSA_CTRL" },
    { ERR_FUNC(DSA_F_PKEY_DSA_KEYGEN), "PKEY_DSA_KEYGEN" },
    { ERR_FUNC(DSA_F_SIG_CB), "SIG_CB" },
    { 0, NULL }
};

static ERR_STRING_DATA DSA_str_reasons[] = {
    { ERR_REASON(DSA_R_BAD_Q_VALUE), "bad q value" },
    { ERR_REASON(DSA_R_BN_DECODE_ERROR), "bn decode error" },
    { ERR_REASON(DSA_R_BN_ERROR), "bn error" },
    { ERR_REASON(DSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE),
     "data too large for key size" },
    { ERR_REASON(DSA_R_DECODE_ERROR), "decode error" },
    { ERR_REASON(DSA_R_INVALID_DIGEST_TYPE), "invalid digest type" },
    { ERR_REASON(DSA_R_INVALID_PARAMETERS), "invalid parameters" },
    { ERR_REASON(DSA_R_MISSING_PARAMETERS), "missing parameters" },
    { ERR_REASON(DSA_R_MODULUS_TOO_LARGE), "modulus too large" },
    { ERR_REASON(DSA_R_NEED_NEW_SETUP_VALUES), "need new setup values" },
    { ERR_REASON(DSA_R_NO_PARAMETERS_SET), "no parameters set" },
    { ERR_REASON(DSA_R_PARAMETER_ENCODING_ERROR), "parameter encoding error" },
    { ERR_REASON(DSA_R_Q_NOT_PRIME), "q not prime" },
    { 0, NULL }
};

#endif

void ERR_load_DSA_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(DSA_str_functs[0].error) == NULL) {
        ERR_load_strings(0, DSA_str_functs);
        ERR_load_strings(0, DSA_str_reasons);
    }
#endif
}
