/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/conf.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_CONF, func, 0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_CONF, 0, reason)

static ERR_STRING_DATA CONF_str_functs[] = {
    { ERR_FUNC(CONF_F_CONF_DUMP_FP), "CONF_DUMP_FP" },
    { ERR_FUNC(CONF_F_CONF_LOAD), "CONF_LOAD" },
    { ERR_FUNC(CONF_F_CONF_LOAD_BIO), "CONF_LOAD_BIO" },
    { ERR_FUNC(CONF_F_CONF_LOAD_FP), "CONF_LOAD_FP" },
    { ERR_FUNC(CONF_F_CONF_MODULES_LOAD), "CONF_MODULES_LOAD" },
    { ERR_FUNC(CONF_F_CONF_PARSE_LIST), "CONF_PARSE_LIST" },
    { ERR_FUNC(CONF_F_DEF_LOAD), "DEF_LOAD" },
    { ERR_FUNC(CONF_F_DEF_LOAD_BIO), "DEF_LOAD_BIO" },
    { ERR_FUNC(CONF_F_MODULE_INIT), "MODULE_INIT" },
    { ERR_FUNC(CONF_F_MODULE_LOAD_DSO), "MODULE_LOAD_DSO" },
    { ERR_FUNC(CONF_F_MODULE_RUN), "MODULE_RUN" },
    { ERR_FUNC(CONF_F_NCONF_DUMP_BIO), "NCONF_DUMP_BIO" },
    { ERR_FUNC(CONF_F_NCONF_DUMP_FP), "NCONF_DUMP_FP" },
    { ERR_FUNC(CONF_F_NCONF_GET_NUMBER), "NCONF_GET_NUMBER" },
    { ERR_FUNC(CONF_F_NCONF_GET_NUMBER_E), "NCONF_GET_NUMBER_E" },
    { ERR_FUNC(CONF_F_NCONF_GET_SECTION), "NCONF_GET_SECTION" },
    { ERR_FUNC(CONF_F_NCONF_GET_STRING), "NCONF_GET_STRING" },
    { ERR_FUNC(CONF_F_NCONF_LOAD), "NCONF_LOAD" },
    { ERR_FUNC(CONF_F_NCONF_LOAD_BIO), "NCONF_LOAD_BIO" },
    { ERR_FUNC(CONF_F_NCONF_LOAD_FP), "NCONF_LOAD_FP" },
    { ERR_FUNC(CONF_F_NCONF_NEW), "NCONF_NEW" },
    { ERR_FUNC(CONF_F_STR_COPY), "STR_COPY" },
    { 0, NULL }
};

static ERR_STRING_DATA CONF_str_reasons[] = {
    { ERR_REASON(CONF_R_ERROR_LOADING_DSO), "error loading dso" },
    { ERR_REASON(CONF_R_LIST_CANNOT_BE_NULL), "list cannot be null" },
    { ERR_REASON(CONF_R_MISSING_CLOSE_SQUARE_BRACKET),
     "missing close square bracket" },
    { ERR_REASON(CONF_R_MISSING_EQUAL_SIGN), "missing equal sign" },
    { ERR_REASON(CONF_R_MISSING_FINISH_FUNCTION), "missing finish function" },
    { ERR_REASON(CONF_R_MISSING_INIT_FUNCTION), "missing init function" },
    { ERR_REASON(CONF_R_MODULE_INITIALIZATION_ERROR),
     "module initialization error" },
    { ERR_REASON(CONF_R_NO_CLOSE_BRACE), "no close brace" },
    { ERR_REASON(CONF_R_NO_CONF), "no conf" },
    { ERR_REASON(CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE),
     "no conf or environment variable" },
    { ERR_REASON(CONF_R_NO_SECTION), "no section" },
    { ERR_REASON(CONF_R_NO_SUCH_FILE), "no such file" },
    { ERR_REASON(CONF_R_NO_VALUE), "no value" },
    { ERR_REASON(CONF_R_UNABLE_TO_CREATE_NEW_SECTION),
     "unable to create new section" },
    { ERR_REASON(CONF_R_UNKNOWN_MODULE_NAME), "unknown module name" },
    { ERR_REASON(CONF_R_VARIABLE_HAS_NO_VALUE), "variable has no value" },
    { 0, NULL }
};

#endif

void ERR_load_CONF_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(CONF_str_functs[0].error) == NULL) {
        ERR_load_strings(0, CONF_str_functs);
        ERR_load_strings(0, CONF_str_reasons);
    }
#endif
}
