/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/hmac.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_HMAC, func, 0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_HMAC, 0, reason)

static ERR_STRING_DATA HMAC_str_functs[] = {
    { 0, NULL }
};

static ERR_STRING_DATA HMAC_str_reasons[] = {
    { 0, NULL }
};

#endif

void ERR_load_HMAC_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(HMAC_str_functs[0].error) == NULL) {
        ERR_load_strings(0, HMAC_str_functs);
        ERR_load_strings(0, HMAC_str_reasons);
    }
#endif
}
