/*
 * Copyright 2002-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */
/* ====================================================================
 * Copyright 2002 Sun Microsystems, Inc. ALL RIGHTS RESERVED.
 *
 * The Elliptic Curve Public-Key Crypto Library (ECC Code) included
 * herein is developed by SUN MICROSYSTEMS, INC., and is contributed
 * to the OpenSSL project.
 *
 * The ECC Code is licensed pursuant to the OpenSSL open source
 * license provided below.
 *
 * The ECDH software is originally written by Douglas Stebila of
 * Sun Microsystems Laboratories.
 *
 */

#ifndef HEADER_ECDH_H
#define HEADER_ECDH_H

#include <openssl/base.h>
#include <openssl/ec.h>
#ifndef OPENSSL_NO_DEPRECATED
#include <openssl/bn.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define EC_FLAG_COFACTOR_ECDH 0x1000

VIGORTLS_EXPORT const ECDH_METHOD *ECDH_OpenSSL(void);

VIGORTLS_EXPORT void ECDH_set_default_method(const ECDH_METHOD *);
VIGORTLS_EXPORT const ECDH_METHOD *ECDH_get_default_method(void);
VIGORTLS_EXPORT int ECDH_set_method(EC_KEY *, const ECDH_METHOD *);

VIGORTLS_EXPORT int ECDH_compute_key(void *out, size_t outlen,
                                     const EC_POINT *pub_key, EC_KEY *ecdh,
                                     void *(*KDF)(const void *in, size_t inlen,
                                                  void *out, size_t *outlen));

VIGORTLS_EXPORT int ECDH_get_ex_new_index(long argl, void *argp,
                                          CRYPTO_EX_new *new_func,
                                          CRYPTO_EX_dup *dup_func,
                                          CRYPTO_EX_free *free_func);
VIGORTLS_EXPORT int ECDH_set_ex_data(EC_KEY *d, int idx, void *arg);
VIGORTLS_EXPORT void *ECDH_get_ex_data(EC_KEY *d, int idx);

VIGORTLS_EXPORT int ECDH_KDF_X9_62(uint8_t *out, size_t outlen,
                                   const uint8_t *Z, size_t Zlen,
                                   const uint8_t *sinfo, size_t sinfolen,
                                   const EVP_MD *md);

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
VIGORTLS_EXPORT void ERR_load_ECDH_strings(void);

/* Error codes for the ECDH functions. */

/* Function codes. */
# define ECDH_F_ECDH_CHECK                                102
# define ECDH_F_ECDH_COMPUTE_KEY                          100
# define ECDH_F_ECDH_DATA_NEW_METHOD                      101

/* Reason codes. */
# define ECDH_R_KDF_FAILED                                102
# define ECDH_R_NO_PRIVATE_VALUE                          100
# define ECDH_R_POINT_ARITHMETIC_FAILURE                  101

#ifdef  __cplusplus
}
#endif
#endif
